language: python
cache: pip
python:
- '3.7'
install:
- pip install awscli
- pip install aws-sam-cli
jobs:
  include:
    - stage: test
      script:
        - pip install pytest
        - pip install -e .
        - pytest . -v
    - stage: deploy
      script:
        - sam validate
        - sam build --debug
        - sam package --s3-bucket travis-web-deployment-bucket --output-template-file out.yml --region us-east-1
        - sam deploy --template-file out.yml --stack-name modelwatch --region us-east-1 --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
      skip_cleanup: true
      if: branch = master
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: your-encrypted-aws-access-key-id
  - secure: your-encrypted-aws-secret-access-key
